### PR TITLE
guild config cmd

### PR DESCRIPTION
**Pull request by BaitGod01**
cmd finished (i think)
each event updates config accordingly

### CODE REVIEW

**Comment by BaitGod01** [comment]
Oh also i forgot how to change the col on the table while in live production I did it via offline and manually updated it

**Comment by BaitGod01** [comment]
Whats left todo after this? trade system?

**Comment by klerikdust** [comment]
> Oh also i forgot how to change the col on the table while in live production I did it via offline and manually updated it

@BaitGod01
You are probably able to execute the ALTER TABLE statement through >db command, so we are basically updating it on-air. This. is similar to how you migrate data from old table to new table with the same table name. 
We can also do it manually as you suggested, the only drawback here is there will be short downtime during the process.

The first option is preferable honestly (but you should ensure the statement is working as expected using your localhost first).

**Comment by klerikdust** [comment]
> Whats left todo after this? trade system?

@BaitGod01
I've kept this list on track in the kanban board. Check it out.
[https://github.com/klerikdust/anniediscord/projects/4](https://github.com/klerikdust/anniediscord/projects/4)

**Comment by BaitGod01** [comment]
completely forgot bout the project board tbh, and ill create the alter table function rn

**Comment by BaitGod01** [comment]
hey naph when u get a chance check your discord dms

**Pull request merged**
