### PR TITLE
v7.0.0

### PR DESCRIPTION
**Pull request by Moore2021**

### CODE REVIEW

**Comment by Moore2021** [comment]
i updated the references but will need u to help fix positioning of elements

**Comment by klerikdust** [comment]
image
@Moore2021 which version of discord.js is required for this PR? I tried installing `v12.2.0` and apparently all commands that using Pistachio.reply() cannot be used, and it gives me error log. Checkout the screenshot.

**Comment by Moore2021** [comment]
The node packages all need updates, discord.js will be 12.0.2, snekfetch is node-fetch, canvas-constructor is 4.2. All of these you have to make sure are correct one thing u might have todo is nuke your node modules folder and reinstall with "npm i -d -m"

**Comment by klerikdust** [comment]
**This version requires version of Node.js to be at least v12.18.3**

**Pull request merged**
