### PR TITLE
welcome module

### PR DESCRIPTION
**Pull request by BaitGod01**
the welcome module is now modular and uses settings set in config

### CODE REVIEW

**Comment by BaitGod01** [comment]
**Custom Guild Configurations** type:feature
This module gives each server owner the flexibility of setting up their own configurations of Annie such as:
- Log Channel *?? whats this*
- Target Like System channel *?? huh*
- Trending/Featured SYstem *don't know how todo this one yet*
- Toggle for Welcomer and the target channel for it. *done*

**Comment by BaitGod01** [comment]
Thinking some things thru, we probably should have server-side Exp and ac instead of global, or at least Exp... also could you help me do that user validate thing?

**Comment by klerikdust** [comment]
> **Custom Guild Configurations** type:feature
> This module gives each server owner the flexibility of setting up their own configurations of Annie such as:
> - Log Channel *?? whats this*
> - Target Like System channel *?? huh*
> - Trending/Featured System *don't know how todo this one yet*
> - Toggle for Welcomer and the target channel for it. *done*

@BaitGod01 
**Log channel** is the target channel for sending log message like joined member, leaving, deleted message, etc. Of course this can be toggled just like the welcomer module
And about the **Like System**, is the one that reacts ❤ to a message and consecutively tracking it.

**Comment by klerikdust** [comment]
> Thinking some things thru, we probably should have server-side Exp and ac instead of global, or at least Exp... also could you help me do that user validate thing?

I've added this task into our roadmap!

**Pull request merged**
